### ISSUE TITLE
Missing licence information

### ISSUE THREAD

**Issue by peterjc** [biocore/Platypus-Conquistador#14]
According to ``Platypus-Conquistador/platypus/__init__.py`` the code is under the GPL licence (version not stated). If so, I would expect the root folder to include a file called ``COPYING`` containing the GPL licence. Alternatively, calling the file ``LICENSE`` (or ``LICENSE.md`` etc if using markup) is common.

It would be nice to add a line to the main ``README.md`` file too.

**Comment by ElDeveloper** [comment]
:+1: makes perfect sense!
