### ISSUE TITLE
Move command line interfaces to use click

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/Platypus-Conquistador#9]

**Comment by ElDeveloper** [comment]
There's a tiny problem with this, if we move to click it doesn't seem like there's an easy way to auto-generate HTML docs from the command line interface. If this is a sacrifice we are ok with doing, let's go for it, otherwise we can:

- Write our own HTML doc generator.
- Use qcli (for the time being).

**Comment by antgonza** [comment]
The use command line interface use cases should be really simple so
HTML should be fine. We should also add a comment on the contributing
file so changes on the CLI should be reflected on the HTML CLI file.

**Comment by ElDeveloper** [comment]
Ok, so click is ok? Tutorials can still be written in RST, it's just
that the auto-generated docs, like these
http://qiime.org/scripts/add_alpha_to_mapping_file.html , can't be made
(without some custom code) for click-based scripts.

**Comment by antgonza** [comment]
Yup, I think is fine.

**Comment by ElDeveloper** [comment]
Thanks for confirming!
